// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKSvpbS-nvL9DEYgNTGNkkK76mXgggbHE',
    appId: '1:116396092394:web:95809f64e81fa484d16093',
    messagingSenderId: '116396092394',
    projectId: 'cca-flutter-app',
    authDomain: 'cca-flutter-app.firebaseapp.com',
    storageBucket: 'cca-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRMI0XWnzvn0YEKilbyZf90MSAMvD5z9k',
    appId: '1:116396092394:android:3cf4d2445317127cd16093',
    messagingSenderId: '116396092394',
    projectId: 'cca-flutter-app',
    storageBucket: 'cca-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUnhwL4gctX2fkhGkgdzgX7o-P1MDrOnE',
    appId: '1:116396092394:ios:b8243e8deee3cb33d16093',
    messagingSenderId: '116396092394',
    projectId: 'cca-flutter-app',
    storageBucket: 'cca-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.cca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUnhwL4gctX2fkhGkgdzgX7o-P1MDrOnE',
    appId: '1:116396092394:ios:b8243e8deee3cb33d16093',
    messagingSenderId: '116396092394',
    projectId: 'cca-flutter-app',
    storageBucket: 'cca-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.cca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKSvpbS-nvL9DEYgNTGNkkK76mXgggbHE',
    appId: '1:116396092394:web:e356ff55e8fde06cd16093',
    messagingSenderId: '116396092394',
    projectId: 'cca-flutter-app',
    authDomain: 'cca-flutter-app.firebaseapp.com',
    storageBucket: 'cca-flutter-app.firebasestorage.app',
  );
}
